{{ HTML::script('admin/js/jquery.min.js') }}
{{ HTML::script('admin/js/bootstrap.min.js') }}
{{ HTML::script('admin/js/jquery-ui.min.js') }}
{{ HTML::script('admin/js/raphael-min.js') }}
<!-- Morris.js charts -->
{{--{{ HTML::script('admin/js/plugins/morris/morris.min.js') }}--}}
{{ HTML::script('admin/js/plugins/sparkline/jquery.sparkline.min.js') }}
{{ HTML::script('admin/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}
{{ HTML::script('admin/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}
{{ HTML::script('admin/js/plugins/jqueryKnob/jquery.knob.js') }}
{{ HTML::script('admin/js/plugins/daterangepicker/daterangepicker.js') }}
{{ HTML::script('admin/js/plugins/datepicker/bootstrap-datepicker.js') }}
{{ HTML::script('//cdn.ckeditor.com/4.4.3/standard/ckeditor.js') }}
{{ HTML::script('admin/js/plugins/iCheck/icheck.min.js') }}
{{ HTML::script('admin/js/plugins/datatables/jquery.dataTables.js') }}
{{ HTML::script('admin/js/plugins/datatables/dataTables.bootstrap.js') }}
{{ HTML::script('admin/js/dropzone.js') }}
{{ HTML::script('admin/js/laravel.js') }}
{{ HTML::script('admin/js/AdminLTE/app.js') }}
{{--{{ HTML::script('admin/js/AdminLTE/dashboard.js') }}--}}
